# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import model_pb2 as model__pb2


class PredictStub(object):
  """Define the service :
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.classify_review = channel.unary_unary(
        '/Predict/classify_review',
        request_serializer=model__pb2.Text.SerializeToString,
        response_deserializer=model__pb2.Prediction.FromString,
        )


class PredictServicer(object):
  """Define the service :
  """

  def classify_review(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'classify_review': grpc.unary_unary_rpc_method_handler(
          servicer.classify_review,
          request_deserializer=model__pb2.Text.FromString,
          response_serializer=model__pb2.Prediction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Predict', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
