# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: databroker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='databroker.proto',
  package='bidirectional_databroker',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61tabroker.proto\x12\x18\x62idirectional_databroker\"_\n\rBrokerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07sensor1\x18\x02 \x01(\x02\x12\x0f\n\x07sensor2\x18\x03 \x01(\x02\x12\x0f\n\x07sensor3\x18\x04 \x01(\x02\x12\x0f\n\x07sensor4\x18\x05 \x01(\x02\"0\n\x0e\x42rokerResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nprediction\x18\x02 \x01(\x08\x32\x80\x01\n\rBrokerService\x12o\n\x16\x42idirectionalStreaming\x12\'.bidirectional_databroker.BrokerRequest\x1a(.bidirectional_databroker.BrokerResponse(\x01\x30\x01\x62\x06proto3'
)




_BROKERREQUEST = _descriptor.Descriptor(
  name='BrokerRequest',
  full_name='bidirectional_databroker.BrokerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bidirectional_databroker.BrokerRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor1', full_name='bidirectional_databroker.BrokerRequest.sensor1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor2', full_name='bidirectional_databroker.BrokerRequest.sensor2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor3', full_name='bidirectional_databroker.BrokerRequest.sensor3', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor4', full_name='bidirectional_databroker.BrokerRequest.sensor4', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=141,
)


_BROKERRESPONSE = _descriptor.Descriptor(
  name='BrokerResponse',
  full_name='bidirectional_databroker.BrokerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bidirectional_databroker.BrokerResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='bidirectional_databroker.BrokerResponse.prediction', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['BrokerRequest'] = _BROKERREQUEST
DESCRIPTOR.message_types_by_name['BrokerResponse'] = _BROKERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrokerRequest = _reflection.GeneratedProtocolMessageType('BrokerRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROKERREQUEST,
  '__module__' : 'databroker_pb2'
  # @@protoc_insertion_point(class_scope:bidirectional_databroker.BrokerRequest)
  })
_sym_db.RegisterMessage(BrokerRequest)

BrokerResponse = _reflection.GeneratedProtocolMessageType('BrokerResponse', (_message.Message,), {
  'DESCRIPTOR' : _BROKERRESPONSE,
  '__module__' : 'databroker_pb2'
  # @@protoc_insertion_point(class_scope:bidirectional_databroker.BrokerResponse)
  })
_sym_db.RegisterMessage(BrokerResponse)



_BROKERSERVICE = _descriptor.ServiceDescriptor(
  name='BrokerService',
  full_name='bidirectional_databroker.BrokerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=194,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='BidirectionalStreaming',
    full_name='bidirectional_databroker.BrokerService.BidirectionalStreaming',
    index=0,
    containing_service=None,
    input_type=_BROKERREQUEST,
    output_type=_BROKERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROKERSERVICE)

DESCRIPTOR.services_by_name['BrokerService'] = _BROKERSERVICE

# @@protoc_insertion_point(module_scope)
