# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tensorboard_pb2 as tensorboard__pb2


class TensorboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.loggging = channel.unary_unary(
                '/Tensorboard/loggging',
                request_serializer=tensorboard__pb2.Empty.SerializeToString,
                response_deserializer=tensorboard__pb2.LoggingStatus.FromString,
                )


class TensorboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def loggging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TensorboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'loggging': grpc.unary_unary_rpc_method_handler(
                    servicer.loggging,
                    request_deserializer=tensorboard__pb2.Empty.FromString,
                    response_serializer=tensorboard__pb2.LoggingStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Tensorboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tensorboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def loggging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tensorboard/loggging',
            tensorboard__pb2.Empty.SerializeToString,
            tensorboard__pb2.LoggingStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
