# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorboard.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11tensorboard.proto\"\x07\n\x05\x45mpty\"\x1f\n\rLoggingStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x31\n\x0bTensorboard\x12\"\n\x08loggging\x12\x06.Empty\x1a\x0e.LoggingStatusb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)


_LOGGINGSTATUS = _descriptor.Descriptor(
  name='LoggingStatus',
  full_name='LoggingStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='LoggingStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['LoggingStatus'] = _LOGGINGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'tensorboard_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

LoggingStatus = _reflection.GeneratedProtocolMessageType('LoggingStatus', (_message.Message,), {
  'DESCRIPTOR' : _LOGGINGSTATUS,
  '__module__' : 'tensorboard_pb2'
  # @@protoc_insertion_point(class_scope:LoggingStatus)
  })
_sym_db.RegisterMessage(LoggingStatus)



_TENSORBOARD = _descriptor.ServiceDescriptor(
  name='Tensorboard',
  full_name='Tensorboard',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=63,
  serialized_end=112,
  methods=[
  _descriptor.MethodDescriptor(
    name='loggging',
    full_name='Tensorboard.loggging',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_LOGGINGSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TENSORBOARD)

DESCRIPTOR.services_by_name['Tensorboard'] = _TENSORBOARD

# @@protoc_insertion_point(module_scope)
