apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-classification-service
spec:
  selector:
    app: sentiment-analysis-classification
  ports:
  - protocol: "TCP"
    port: 50001
    targetPort: 50053
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-classification
spec:
  selector:
    matchLabels:
      app: sentiment-analysis-classification
  replicas: 2
  template:
    metadata:
      labels:
        app: sentiment-analysis-classification
    spec:
      containers:
      - name: sentiment-analysis-classification
        image: sentiment-analysis-classification:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50053
