# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class get_next_rowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_next_row = channel.unary_unary(
                '/get_next_row/get_next_row',
                request_serializer=model__pb2.Empty.SerializeToString,
                response_deserializer=model__pb2.Features.FromString,
                )


class get_next_rowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_next_row(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_next_rowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_next_row': grpc.unary_unary_rpc_method_handler(
                    servicer.get_next_row,
                    request_deserializer=model__pb2.Empty.FromString,
                    response_serializer=model__pb2.Features.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'get_next_row', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_next_row(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_next_row(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/get_next_row/get_next_row',
            model__pb2.Empty.SerializeToString,
            model__pb2.Features.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
