# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import classifier_model_pb2 as classifier__model__pb2


class ClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeatureNames = channel.unary_unary(
                '/Classifier/GetFeatureNames',
                request_serializer=classifier__model__pb2.DataID.SerializeToString,
                response_deserializer=classifier__model__pb2.FeatureNames.FromString,
                )
        self.GetPrediction = channel.unary_unary(
                '/Classifier/GetPrediction',
                request_serializer=classifier__model__pb2.Request.SerializeToString,
                response_deserializer=classifier__model__pb2.ClassifierResult.FromString,
                )


class ClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFeatureNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeatureNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureNames,
                    request_deserializer=classifier__model__pb2.DataID.FromString,
                    response_serializer=classifier__model__pb2.FeatureNames.SerializeToString,
            ),
            'GetPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrediction,
                    request_deserializer=classifier__model__pb2.Request.FromString,
                    response_serializer=classifier__model__pb2.ClassifierResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Classifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Classifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFeatureNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Classifier/GetFeatureNames',
            classifier__model__pb2.DataID.SerializeToString,
            classifier__model__pb2.FeatureNames.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Classifier/GetPrediction',
            classifier__model__pb2.Request.SerializeToString,
            classifier__model__pb2.ClassifierResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
